export const URL_PARAMS_TO_STATE = "URL_PARAMS_TO_STATE";
export const UPDATE_QUERYDATES = "UPDATE_QUERYDATES";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const UPDATE_LOADING = "UPDATE_LOADING";
export const UPDATE_DATA = "UPDATE_DATA";

export const ONE_DAY = 86400000;
