const nameMap = {
  "1.cz": ["1.cz"],
  "1&1": ["search.1and1.com"],
  "1und1": ["search.1und1.de"],
  "2gis": ["2gis.ru"],
  "360.cn": ["so.360.cn", "so.com"],
  Abacho: [
    "abacho.de",
    "abacho.com",
    "abacho.co.uk",
    "abacho.at",
    "abacho.fr",
    "abacho.es",
    "abacho.ch",
    "abacho.it"
  ],
  ABCsøk: ["abcsolk.no", "verden.abcsok.no"],
  Acoon: ["acoon.de"],
  Alexa: ["alexa.com"],
  "Alice Adsl": ["rechercher.aliceadsl.fr"],
  "all.by": ["all.by"],
  AllTheWeb: ["alltheweb.com"],
  Altavista: ["altavista.com", "altavista.de", "altavista.fr"],
  Amazon: ["amazon.com"],
  AOL: [
    "aol.com",
    "aolsearch.com",
    "aol.fr",
    "aol.ca",
    "aol.co.uk",
    "aol.de",
    "aolsvc.de",
    "aol.com.mx",
    "aol.com.au",
    "aol.it"
  ],
  APOLL07: ["apollo7.de"],
  "Apollo Latvia": ["apollo.lv"],
  Apontador: ["apontador.com.br"],
  Aport: ["sm.aport.ru"],
  arama: ["arama.com"],
  Arcor: ["arcor.de"],
  Arianna: ["arianna.libero.it", "arianna.com"],
  Ask: [
    "ask.com",
    "ask.reference.com",
    "askkids.com",
    "ask.co.uk",
    "qbyrd.com",
    "search-results.com"
  ],
  Atlas: ["searchatlas.centrum.cz"],
  Austronaut: ["austronaut.at"],
  Babylon: ["babylon.com"],
  Badoo: ["badoo.com"],
  Baidu: ["baidu.com"],
  Bebo: ["bebo.com"],
  Biglobe: ["cgi.search.biglobe.ne.jp"],
  Bing: ["bing.com", "msn.com", "bingj.com"],
  BlackPlanet: ["blackplanet.com"],
  blekko: ["blekko.com"],
  Blogdigger: ["blogdigger.com"],
  Blogpulse: ["blogpulse.com"],
  Bluewin: ["search.bluewin.ch"],
  BT: ["search.bt.com"],
  Buzznet: ["buzznet.com"],
  "canoe.ca": ["web.canoe.ca"],
  Centrum: ["search.centrum.cz", "morfeo.centrum.cz"],
  "Certified-Toolbar": ["search.certified-toolbar.com"],
  Charter: ["charter.net"],
  "Classmates.com": ["classmates.com"],
  Clix: ["pesquisa.clix.pt"],
  Comcast: ["search.comcast.net"],
  Compuserve: ["websearch.cs.com"],
  Conduit: ["search.conduit.com"],
  Crawler: ["crawler.com"],
  Cuil: ["cuil.com"],
  Cyworld: ["global.cyworld.com"],
  "Daemon search": ["daemon-search.com"],
  Dalesearch: ["dalesearch.com"],
  DasOertliche: ["dasoertliche.de"],
  DasTelefonbuch: ["www1.dastelefonbuch.de"],
  Daum: ["search.daum.net"],
  Delfi: ["otsing.delfi.ee"],
  "Delfi latvia": ["smart.delfi.lv"],
  Delicious: ["delicious.com"],
  Digg: ["digg.com"],
  Disqus: ["disq.us", "disqus.com"],
  dmoz: ["dmoz.org"],
  Dodo: ["google.dodo.com.au"],
  Donanimhaber: ["donanimhaber.com"],
  Douban: ["douban.com"],
  Dribbble: ["dribbble.com"],
  DuckDuckGo: ["duckduckgo.com"],
  earthlink: ["search.earthlink.net"],
  Ecosia: ["ecosia.org"],
  "Eksi Sozluk": ["Sozluk.com", "sourtimes.org"],
  "El Mundo": ["ariadna.elmundo.es"],
  Eniro: ["eniro.se"],
  eo: ["eo.st"],
  Eurip: ["eurip.com"],
  Euroseek: ["euroseek.com"],
  Everyclick: ["everyclick.com"],
  Exalead: ["exalead.fr", "exalead.com"],
  Excite: [
    "excite.it",
    "excite.fr",
    "excite.de",
    "excite.co.uk",
    "excite.es",
    "excite.nl",
    "excite.com",
    "excite.co.jp"
  ],
  Facebook: ["facebook.com", "fb.me"],
  "Fast Browser Search": ["fastbrowsersearch.com"],
  Fetlife: ["fetlife.com"],
  Finderoo: ["finderoo.com"],
  Findwide: ["search.findwide.com"],
  Fireball: ["fireball.de"],
  Firstfind: ["firstsfind.com"],
  Fixsuche: ["fixsuche.de"],
  Flickr: ["flickr.com"],
  Flix: ["flix.de"],
  Flixster: ["flixster.com"],
  Flyingbird: ["inspsearch.com"],
  Forestle: ["forestle.org", "forestle.org", "forestle.mobi"],
  Fotolog: ["fotolog.com"],
  Foursquare: ["foursquare.com"],
  Francite: ["recherche.francite.com"],
  Free: ["free.fr"],
  Freecause: ["search.freecause.com"],
  Freenet: ["suche.freenet.de"],
  Freshweather: ["fresh-weather.com"],
  FriendFeed: ["friendfeed.com"],
  "Friends Reunited": ["friendsreunited.com"],
  Friendster: ["friendster.com"],
  "Gaia Online": ["gaiaonline.com"],
  GAIS: ["gais.cs.ccu.edu.tw"],
  Geni: ["geni.com"],
  Genieo: ["search.genieo.com"],
  Geona: ["geona.net"],
  Gigablast: ["gigablast.com"],
  GitHub: ["github.com"],
  Globososo: ["searches.globososo.com"],
  GMX: ["suche.gmx.net"],
  Gnadenmeer: ["gnadenmeer.de"],
  Gomeo: ["gomeo.com"],
  goo: ["search.goo.ne.jp"],
  Google: [
    "google.com",
    "google.ac",
    "google.ad",
    "google.com.af",
    "google.com.ag",
    "google.com.ai",
    "google.am",
    "google.it.ao",
    "google.com.ar",
    "google.as",
    "google.at",
    "google.com.au",
    "google.az",
    "google.ba",
    "google.com.bd",
    "google.be",
    "google.bf",
    "google.bg",
    "google.com.bh",
    "google.bi",
    "google.bj",
    "google.com.bn",
    "google.com.bo",
    "google.com.br",
    "google.bs",
    "google.co.bw",
    "google.com.by",
    "google.by",
    "google.com.bz",
    "google.ca",
    "google.com.kh",
    "google.cc",
    "google.cd",
    "google.cf",
    "google.cat",
    "google.cg",
    "google.ch",
    "google.ci",
    "google.co.ck",
    "google.cl",
    "google.cm",
    "google.cn",
    "google.com.co",
    "google.co.cr",
    "google.com.cu",
    "google.cv",
    "google.com.cy",
    "google.cz",
    "google.de",
    "google.dj",
    "google.dk",
    "google.dm",
    "google.com.do",
    "google.dz",
    "google.com.ec",
    "google.ee",
    "google.com.eg",
    "google.es",
    "google.com.et",
    "google.fi",
    "google.com.fj",
    "google.fm",
    "google.fr",
    "google.ga",
    "google.gd",
    "google.ge",
    "google.gf",
    "google.gg",
    "google.com.gh",
    "google.com.gi",
    "google.gl",
    "google.gm",
    "google.gp",
    "google.gr",
    "google.com.gt",
    "google.gy",
    "google.com.hk",
    "google.hn",
    "google.hr",
    "google.ht",
    "google.hu",
    "google.co.id",
    "google.iq",
    "google.ie",
    "google.co.il",
    "google.im",
    "google.co.in",
    "google.io",
    "google.is",
    "google.it",
    "google.je",
    "google.com.jm",
    "google.jo",
    "google.co.jp",
    "google.co.ke",
    "google.ki",
    "google.kg",
    "google.co.kr",
    "google.com.kw",
    "google.kz",
    "google.la",
    "google.com.lb",
    "google.com.lc",
    "google.li",
    "google.lk",
    "google.co.ls",
    "google.lt",
    "google.lu",
    "google.lv",
    "google.com.ly",
    "google.co.ma",
    "google.md",
    "google.me",
    "google.mg",
    "google.mk",
    "google.ml",
    "google.mn",
    "google.ms",
    "google.com.mt",
    "google.mu",
    "google.mv",
    "google.mw",
    "google.com.mx",
    "google.com.my",
    "google.co.mz",
    "google.com.na",
    "google.ne",
    "google.com.nf",
    "google.com.ng",
    "google.com.ni",
    "google.nl",
    "google.no",
    "google.com.np",
    "google.nr",
    "google.nu",
    "google.co.nz",
    "google.com.om",
    "google.com.pa",
    "google.com.pe",
    "google.com.ph",
    "google.com.pk",
    "google.pl",
    "google.pn",
    "google.com.pr",
    "google.ps",
    "google.pt",
    "google.com.py",
    "google.com.qa",
    "google.ro",
    "google.rs",
    "google.ru",
    "google.rw",
    "google.com.sa",
    "google.com.sb",
    "google.sc",
    "google.se",
    "google.com.sg",
    "google.sh",
    "google.si",
    "google.sk",
    "google.com.sl",
    "google.sn",
    "google.sm",
    "google.so",
    "google.st",
    "google.com.sv",
    "google.td",
    "google.tg",
    "google.co.th",
    "google.com.tj",
    "google.tk",
    "google.tl",
    "google.tm",
    "google.to",
    "google.com.tn",
    "google.tn",
    "google.com.tr",
    "google.tt",
    "google.com.tw",
    "google.co.tz",
    "google.com.ua",
    "google.co.ug",
    "google.ae",
    "google.co.uk",
    "google.us",
    "google.com.uy",
    "google.co.uz",
    "google.com.vc",
    "google.co.ve",
    "google.vg",
    "google.co.vi",
    "google.com.vn",
    "google.vu",
    "google.ws",
    "google.co.za",
    "google.co.zm",
    "google.co.zw",
    "google.com"
  ],
  "Goyellow.de": ["goyellow.de"],
  gree: ["gree.jp"],
  "Gule Sider": ["gulesider.no"],
  Haboo: ["habbo.com"],
  "Hacker News": ["news.ycombinator.com"],
  hi5: ["hi5.com"],
  HighBeam: ["highbeam.com"],
  "Hit-Parade": ["hit-parade.com"],
  "Hocam.com": ["hocam.com"],
  Holmes: ["holmes.ge"],
  "Hooseek.com": ["hooseek.com"],
  Hotbot: ["hotbot.com"],
  Hyves: ["hyves.nl"],
  "I-play": ["start.iplay.com"],
  "I.ua": ["search.i.ua"],
  Icerockeet: ["blogs.icerocket.com"],
  ICQ: ["icq.com"],
  "identi.ca": ["identi.ca"],
  Ilse: ["ilse.nl"],
  "Inbox.com": ["inbox.com"],
  "Inci Sozluk": ["inci.sozlukspot.com", "incisozluk.com", "incisozluk.cc"],
  InfoSpace: [
    "clusty.com",
    "dogpile.com",
    "infospace.com",
    "isearch.babylon.com",
    "metacrawler.com",
    "search.kiwee.com",
    "search.magnetic.com",
    "search.searchcompletion.com",
    "start.facemoods.com",
    "webcrawler.com",
    "webfetch.com"
  ],
  Instagram: ["instagram.com"],
  Instela: ["instela.com"],
  Interia: ["google.interia.pl"],
  "ITU Sozluk": ["itusozluk.com"],
  IXquick: ["ixquick.com", "ixquick.de"],
  "Jungle Key": ["junglekey.com", "junglekey.fr"],
  "Jungle Spider": ["jungle-spider.de"],
  Jyxo: ["jyxo.1188.cz"],
  Kataweb: ["kataweb.it"],
  kununu: ["kununu.com"],
  Kvasir: ["kvasir.no"],
  "La Toile Du Quebec Via Google": ["toile.com"],
  "lang-8": ["lang-8.com"],
  "Last.fm": [
    "last.fm",
    "lastfm.ru",
    "lastfm.de",
    "lastfm.es",
    "lastfm.fr",
    "lastfm.it",
    "lastfm.jp",
    "lastfm.pl",
    "lastfm.com.br",
    "lastfm.se",
    "lastfm.com.tr"
  ],
  Latne: ["latne.lv"],
  LinkedIn: ["linkedin.com", "lnkd.in", "android-app://com.linkedin.android"],
  Liveinternet: ["liveinternet.ru"],
  LiveJournal: ["livejournal.ru", "livejournal.com"],
  "Lo.st": ["lo.st"],
  Looksmart: ["looksmart.com"],
  Lycos: ["lycos.com"],
  maailm: ["maailm.com"],
  "Mail.ru": ["mail.ru"],
  Mamma: ["mamma.com"],
  Marktplaats: ["marktplaats.nl"],
  Mastodon: [
    "mastodon.social",
    "mastodon.cloud",
    "mastodon.technology",
    "mastodon.xyz",
    "mastodon.at",
    "mastodon.art",
    "mamot.fr",
    "pawoo.net",
    "mstdn.io",
    "mstdn.jp",
    "friends.nico",
    "ro-mastodon.puyo.jp",
    "quey.org",
    "botsin.space",
    "social.tchncs.de",
    "knzk.me",
    "mastodont.cat",
    "bitcoinhackers.org",
    "fosstodon.org",
    "chaos.social",
    "cybre.space",
    "vis.social"
  ],
  Maxwebsearch: ["maxwebsearch.com"],
  Medium: ["medium.com"],
  Meinestadt: ["meinestadt.de"],
  MeinVZ: ["meinvz.net"],
  Meta: ["meta.ua"],
  "MetaCrawler.de": ["metacrawler.de"],
  Metager: ["meta.rrzn.uni-hannover.de", "metager.de"],
  Metager2: ["metager2.de"],
  "Mister Wong": ["mister-wong.com", "mister-wong.de"],
  Mixi: ["mixi.jp"],
  "MoiKrug.ru": ["moikrug.ru"],
  Monstercrawler: ["monstercrawler.com"],
  Mozbot: ["mozbot.fr", "mozbot.co.uk", "mozbot.com"],
  Multiply: ["multiply.com"],
  "my.mail.ru": ["my.mail.ru"],
  MyHeritage: ["myheritage.com"],
  MyLife: ["mylife.ru"],
  MySearch: ["mysearch.com", "myway.com", "mywebsearch.com"],
  Myspace: ["myspace.com"],
  myYearbook: ["myyearbook.com"],
  Najdi: ["najdi.si"],
  "Nasza-klasa.pl": ["nk.pl"],
  Nate: ["search.nate.com"],
  Naver: ["naver.com"],
  Needtofind: ["ko.search.need2find.com"],
  Neti: ["neti.ee"],
  Netlog: ["netlog.com"],
  Nifty: ["search.nifty.com"],
  Nigma: ["nigma.ru"],
  Odnoklassniki: ["odnoklassniki.ru", "ok.ru"],
  Onet: ["szukaj.onet.pl"],
  "Online.no": ["online.no"],
  "Opplysningen 1881": ["1881.no"],
  Orange: ["busca.orange.es", "search.orange.co.uk", "lemoteur.orange.fr"],
  Orkut: ["orkut.com"],
  Ozone: ["qzone.qq.com"],
  "Paper.li": ["paper.li"],
  Paperball: ["paperball.de"],
  Peepeth: ["peepeth.com"],
  PeoplePC: ["search.peoplepc.com"],
  Picsearch: ["picsearch.com"],
  Pinterest: [
    "pinterest.com",
    "pinterest.ca",
    "pinterest.ch",
    "pinterest.co.uk",
    "pinterest.de",
    "pinterest.dk",
    "pinterest.es",
    "pinterest.fr",
    "pinterest.ie",
    "pinterest.jp",
    "pinterest.nz",
    "pinterest.pt",
    "pinterest.se"
  ],
  Plaxo: ["plaxo.com"],
  Plazoo: ["plazoo.com"],
  Pocket: ["getpocket.com"],
  "Poisk.ru": ["poisk.ru"],
  PriceRunner: ["pricerunner.co.uk"],
  qip: ["search.qip.ru"],
  Qualigo: ["qualigo.at", "qualigo.ch", "qualigo.de", "qualigo.nl"],
  Quora: ["quora.com"],
  Qwant: ["qwant.com"],
  Qzone: ["qzone.qq.com"],
  Rakuten: ["websearch.rakuten.co.jp"],
  Rambler: ["nova.rambler.ru"],
  Reddit: [
    "reddit.com",
    "np.reddit.com",
    "pay.reddit.com",
    "android-app://com.laurencedawson.reddit_sync",
    "android-app://com.laurencedawson.reddit_sync.pro"
  ],
  Renren: ["renren.com"],
  "Road Runner Search": ["search.rr.com"],
  RPMFind: ["rpmfind.net", "fr2.rpmfind.net"],
  Sapo: ["pesquisa.sapo.pt"],
  "Search This": ["searchthis.com"],
  "Search.ch": ["search.ch"],
  "Search.com": ["search.com"],
  Searchalot: ["searchalot.com"],
  SearchCanvas: ["searchcanvas.com"],
  Searchy: ["searchy.co.uk"],
  Seznam: ["search.seznam.cz"],
  Sharelook: ["sharelook.fr"],
  Shenma: ["sm.cn"],
  Skynet: ["skynet.be"],
  Skype: ["web.skype.com"],
  Skyrock: ["skyrock.com"],
  Slack: ["android-app://com.slack"],
  Snapdo: ["search.snapdo.com"],
  Softonic: ["search.softonic.com"],
  Sogou: ["sougou.com", "soso.com"],
  "Sonico.com": ["sonico.com"],
  SoSoDesk: ["sosodesktop.com"],
  Sourceforge: ["sourceforge.net"],
  StackOverflow: ["stackoverflow.com"],
  Startpagina: ["startgoogle.startpagina.nl"],
  Startsiden: ["startsiden.no"],
  StudiVZ: ["studivz.net"],
  StumbleUpon: ["stumbleupon.com"],
  "suche.info": ["suche.info"],
  "Suchmaschine.com": ["suchmaschine.com"],
  Suchnase: ["suchnase.de"],
  "T-Online": ["t-online.de"],
  Tagged: ["login.tagged.com"],
  TalkTalk: ["talktalk.co.uk"],
  "Taringa!": ["taringa.net"],
  Technorati: ["technorati.com"],
  Telegram: ["web.telegram.org", "android-app://org.telegram.messenger"],
  Telstra: ["search.media.telstra.com.au"],
  Teoma: ["teoma.com"],
  Terra: ["terra.es", "terra.cl", "terra.com.br"],
  "The Smart Search": ["thesmartsearch.net"],
  Tiscali: ["tiscali.it", "tiscali.cz"],
  Tixuma: ["tixuma.de"],
  Toolbarhome: ["toolbarhome.com"],
  "Trouvez.com": ["trouvez.com"],
  TrovaRapido: ["trovarapido.com"],
  Tuenti: ["tuenti.com"],
  Tumblr: ["tumblr.com", "t.umblr.com"],
  "Tut.by": ["search.tut.by"],
  Twingly: ["twingly.com"],
  Twitter: ["twitter.com", "t.co"],
  "UKR.net": ["search.ukr.net"],
  "Uludag Sozluk": ["uludagsozluk.com", "ulusozluk.com"],
  "uol.com.br": ["uol.com.br"],
  "URL.ORGanizier": ["url.org"],
  V2EX: ["v2ex.com"],
  Viadeo: ["viadeo.com"],
  Vimeo: ["vimeo.com"],
  Vinden: ["vinden.nl"],
  Vindex: ["vindex.nl"],
  Virgilio: ["virgilio.it"],
  Vkontakte: ["vk.com", "vkontakte.ru"],
  "vkrugudruzei.ru": ["vkrugudruzei.ru"],
  "vKruguDruzei.ru": ["vkrugudruzei.ru"],
  Voila: ["search.ke.voila.fr", "lemoteur.fr"],
  Volny: ["web.volny.cz"],
  "Walhello ": ["walhello.info", "walhello.com", "walhello.de", "walhello.nl"],
  WAYN: ["wayn.com"],
  "Web.de": ["suche.web.de"],
  "Web.nl": ["web.nl"],
  Weborama: ["weborama.com"],
  WebSearch: ["websearch.com"],
  WeeWorld: ["weeworld.com"],
  Weibo: ["weibo.com", "t.cn"],
  WhatsApp: ["web.whatsapp.com"],
  Whirlpool: ["forums.whirlpool.net.au"],
  Winamp: ["search.winamp.com"],
  "Windows Live Spaces": ["login.live.com"],
  "Wirtualna Polska": ["szukaj.wp.pl"],
  Witch: ["witch.de"],
  WWW: ["search.www.ee"],
  "X-recherche": ["x-recherche.com"],
  Xanga: ["xanga.com"],
  XING: ["xing.com"],
  "Yahoo!": [
    "yahoo.com",
    "yahoo.co.jp",
    "cercato.it",
    "search.offerbox.com",
    "ys.mirostart.com"
  ],
  Yam: ["search.yam.com"],
  Yandex: [
    "yandex.ru",
    "yandex.ua",
    "yandex.com",
    "yandex.by",
    "yandex.com.tr"
  ],
  Yasni: ["yasni.de", "yasni.com", "yasni.co.uk", "yasni.ch", "yasni.at"],
  Yatedo: ["yatedo.com", "yatedo.fr"],
  Yippy: ["search.yippy.com"],
  YouGoo: ["yougoo.fr"],
  YouTube: ["youtube.com", "youtu.be"],
  Zapmeta: ["zapmeta.com", "zapmeta.nl", "zapmeta.de"],
  Zhongsou: ["p.zhongsou.com"],
  Zoek: ["www3.zoek.nl"],
  Zoeken: ["zoeken.nl"],
  Zoohoo: ["zoohoo.cz"]
};

export const mapURLToName = url => {
  for (const name in nameMap) {
    const match = nameMap[name].find(nameUrl => {
      const regex = new RegExp(`(\/|\.|^)${nameUrl}(\/|$)`);
      return regex.test(url);
    });
    if (match) {
      return name;
    }
  }
  return url;
};

export const mapNameToURLs = name => nameMap[name] || name;
